/*
 * Copyright 2021 Code Intelligence GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_code_intelligence_jazzer_replay_Replayer */

#ifndef _Included_com_code_intelligence_jazzer_replay_Replayer
#define _Included_com_code_intelligence_jazzer_replay_Replayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_code_intelligence_jazzer_replay_Replayer
 * Method:    feedFuzzedDataProvider
 * Signature: ([B)
 */
JNIEXPORT void JNICALL
Java_com_code_1intelligence_jazzer_replay_Replayer_feedFuzzedDataProvider(
    JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
